### ISSUE TITLE
How to change default password?

### ISSUE THREAD

**Issue by LyQuid12** [Oshekher-git/Oshekher-RDP#4]
how to change the default password from "@Oshekher" to what we like. Please reply, Thanks ♡

**Comment by Oshekher** [comment]
https://github.com/Oshekher-git/Oshekher-RDP/blob/main/start.bat

Link: 6 & 19

**Comment by LyQuid12** [comment]
done, but can't

**Comment by LyQuid12** [comment]
I've changed it to a random password like "!Myrdpserver" but still can't

**Comment by Oshekher** [comment]
Change line No 15 in  https://github.com/LyQuid12/Oshekher-RDP/blob/main/.github/workflows/Oshekher.yml from https://raw.githubusercontent.com/Oshekher-git/Oshekher-RDP/main/start.bat to https://raw.githubusercontent.com/LyQuid12/Oshekher-RDP/main/start.bat

**Comment by LyQuid12** [comment]
ok i will try. is it possible to make more than one rdp at the same time?

**Comment by LyQuid12** [comment]
It's working. Thx ☆

**Comment by Oshekher** [comment]
You're welcome ☺️

**Comment by LyQuid12** [comment]
@Oshekher do yo have telegram? so I can chat with you more easily

**Comment by Oshekher** [comment]
T.me/nestmars

**Comment by LyQuid12** [comment]
Great
